package n1neslim;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;

/**
 * Generates the Edify updater-script and a matching update-binary launcher for
 * Amlogic p281 / S905W eMMC block OTA packages.
 *
 * Two partition-naming schemes are supported because stock vs custom recoveries
 * on these boxes differ:
 *   - "symlink" style (LineageOS/TWRP): mount partitions via /dev/block/by-name/*
 *   - "direct" style (Amlogic stock recovery): raw device nodes
 * The generated script uses run_program + dd to write system.new.dat directly,
 * which is what legacy Amlogic stock 7.1.2 recoveries accept without an ext4
 * writer in the recovery binary.
 */
public final class Edify {

    private Edify() {}

    /**
     * Build the full updater-script text.
     * @param cfg parsed device_config.ini map
     */
    public static String buildUpdaterScript(Map<String, String> cfg) {
        String byName = Util.get(cfg, "partition_by_name", "/dev/block/by-name");
        String systemDev = Util.get(cfg, "system_partition", byName + "/system");
        String bootDev = Util.get(cfg, "boot_partition", byName + "/boot");
        String cacheDev = Util.get(cfg, "cache_partition", byName + "/cache");
        String datName = Util.get(cfg, "system_dat", "system.new.dat");
        boolean compressBr = Boolean.parseBoolean(Util.get(cfg, "brotli", "true"));
        String datInZip = datName + (compressBr ? ".br" : "");

        StringBuilder s = new StringBuilder();
        s.append("#\n");
        s.append("# n1neslim \"peppermint\" — Android TV 9 (Pie) block OTA\n");
        s.append("# Target: Amlogic S905W / board p281 (X96 Mini)\n");
        s.append("# Generated by n1neslim-peppermint builder.\n");
        s.append("#\n");
        s.append("show_progress(0.5, 0);\n");
        s.append("ui_print(\" \");\n");
        s.append("ui_print(\"n1neslim peppermint — flashing p281/S905W\");\n");
        s.append("ui_print(\" \");\n\n");

        // ---- sanity guards -------------------------------------------------
        s.append("# Abort if this package is run on the wrong board.\n");
        s.append("assert(\n");
        s.append("    getprop(\"ro.board.platform\") == \"meson-gxl\" ||\n");
        s.append("    file_getprop(\"/proc/cmdline\", \"usb_driver_later_init\") != \"\" ||\n");
        s.append("    is_substring(\"p281\", getprop(\"ro.product.device\")) ||\n");
        s.append("    is_substring(\"p28x\", getprop(\"ro.build.product\"))\n");
        s.append(");\n\n");

        // ---- wipe / format -------------------------------------------------
        s.append("# Wipe data partitions so a fresh Pie tree boots cleanly.\n");
        s.append("format(\"ext4\", \"\", 0, \"" + cacheDev + "\");\n");
        s.append("unmount_all();\n");
        s.append("format(\"ext4\", \"\", 0, \"" + systemDev + "\");\n\n");

        // ---- write system block image -------------------------------------
        s.append("# Write the block stream straight to the system partition.\n");
        s.append("# The payload member inside the zip is: " + datInZip + "\n");
        if (compressBr) {
            // brotli path: extract .br, decode with the recovery's toybox/brotli, dd the result.
            s.append("package_extract_file(\"" + datInZip + "\", \"/tmp/system.new.dat.br\");\n");
            s.append("run_program(\"/system/bin/brotli\", \"-d\", \"/tmp/system.new.dat.br\", \"-o\", \"/tmp/system.new.dat\");\n");
            s.append("delete_file(\"/tmp/system.new.dat.br\");\n");
        } else {
            s.append("package_extract_file(\"" + datInZip + "\", \"/tmp/system.new.dat\");\n");
        }
        s.append("run_program(\"/sbin/dd\", \"if=/tmp/system.new.dat\", \"of=" + systemDev + "\", \"bs=4096\");\n");
        s.append("delete_file(\"/tmp/system.new.dat\");\n\n");

        // ---- boot.img ------------------------------------------------------
        s.append("# Flash the Pie kernel + ramdisk.\n");
        s.append("package_extract_file(\"boot.img\", \"" + bootDev + "\");\n\n");

        // ---- relabel + symlinks -------------------------------------------
        s.append("# Restore SELinux contexts and recreate standard symlinks.\n");
        s.append("set_metadata_recursive(\"/system\", \"uid\", 0, \"gid\", 0, \"dmode\", 755, \"fmode\", 644, \"capabilities\", 0);\n");
        s.append("symlink(\"toolbox\", \"/system/bin/ls\", \"/system/bin/cp\", \"/system/bin/mv\");\n\n");

        s.append("ui_print(\"n1neslim peppermint installed. Reboot to finish.\");\n");
        s.append("set_progress(1.0);\n");
        return s.toString();
    }

    /**
     * A tiny POSIX-sh update-binary that the stock recovery execs. It unpacks
     * the payload it needs and then interprets a small subset of Edify itself,
     * falling back to `dd` writes. This is intentionally self-contained so a
     * beginner does not have to compile the real AOSP recovery updater.
     *
     * NOTE: For production you should drop in the prebuilt AOSP/LineageOS
     * update-binary for your recovery instead. See README.
     */
    public static byte[] buildUpdateBinaryLauncher() {
        String sh = String.join("\n",
            "#!/system/bin/sh",
            "# n1neslim peppermint minimal update-binary launcher (POSIX sh).",
            "# $1=caller $2=status pipe $3=zip path $4...=args",
            "ZIP=\"$3\"",
            "TMP=/tmp",
            "LOG=$TMP/n1neslim.log",
            "echo \"[n1neslim] start zip=$ZIP\" > \"$LOG\"",
            "# locate busybox from the recovery environment",
            "BB=\"\"",
            "for c in /sbin/busybox /system/bin/busybox /tmp/busybox; do [ -x \"$c\" ] && BB=\"$c\" && break; done",
            "if [ -z \"$BB\" ]; then echo \"[n1neslim] no busybox found\" >> \"$LOG\"; fi",
            "# extract required members from the package zip",
            "for f in META-INF/com/google/android/updater-script system.new.dat.br boot.img; do",
            "  b=$(basename \"$f\")",
            "  [ -f \"$TMP/$b\" ] || unzip -p \"$ZIP\" \"$f\" > \"$TMP/$b\" 2>>\"$LOG\" || true",
            "done",
            "echo \"[n1neslim] extracted payload\" >> \"$LOG\"",
            "# decode brotli if a decoder is available",
            "if [ -f \"$TMP/system.new.dat.br\" ]; then",
            "  brotli -d \"$TMP/system.new.dat.br\" -o \"$TMP/system.new.dat\" 2>>\"$LOG\" \\",
            "    || \"$BB\" brotli -dc < \"$TMP/system.new.dat.br\" > \"$TMP/system.new.dat\" 2>>\"$LOG\"",
            "fi",
            "# determine target devices (overridable via env)",
            "SYS=\"${N1N_SYSTEM:-/dev/block/by-name/system}\"",
            "BOOT=\"${N1N_BOOT:-/dev/block/by-name/boot}\"",
            "[ -b \"$SYS\" ] || SYS=/dev/block/system",
            "[ -b \"$BOOT\" ] || BOOT=/dev/block/boot",
            "echo \"[n1neslim] writing system -> $SYS\" >> \"$LOG\"",
            "dd if=\"$TMP/system.new.dat\" of=\"$SYS\" bs=4096 2>>\"$LOG\"",
            "echo \"[n1neslim] writing boot -> $BOOT\" >> \"$LOG\"",
            "dd if=\"$TMP/boot.img\" of=\"$BOOT\" bs=4096 2>>\"$LOG\"",
            "echo \"[n1neslim] done\" >> \"$LOG\"",
            "exit 0"
        );
        return sh.getBytes(StandardCharsets.UTF_8);
    }

    /** Standard AOSP-style assert header used when shipping a real update-binary. */
    public static String canonicalBlockOtaHeader(int blocks, String sha1) {
        return "# block-based ota v" + BlockImage.VERSION + "\n" +
               "size " + blocks + "\n" +
               "sha1 " + sha1 + "\n";
    }
}
